config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"
  resource "game", only: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/games_controller.rb
# frozen_string_literal: true
require 'pry'

class GamesController < ApplicationController
  DEFAULT_ITEMS_LIST = %w[rock paper scissors].freeze
  before_action :set_items_list

  def index; end

  def new
    @throw_service = ThrowService.new(params[:user_throw], @items_list)
    @result = @throw_service.call
  end

  private

  def set_items_list
    custom_list = params[:items_list]&.split(',')&.map(&:strip)

    if custom_list.nil? || custom_list.empty?
      @items_list ||= DEFAULT_ITEMS_LIST
    else
      @items_list = custom_list
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="container">
  <h1 class="container-header">
    ROCK – PAPER – SCISSORS
  </h1>
  <p class="container-description">
    Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no tools. The idea is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an outcome.
  </p>
  <div class="game">
    <h2 class="game-title">
      SELECT YOUR BET
    </h2>
    <div class="game-body">
      <% @items_list.each do |item|%>
        <%= link_to new_game_path(user_throw: item), data: { turbo_frame: 'modal' } do %>
          <div class="game-item">
            <% if @items_list == GamesController::DEFAULT_ITEMS_LIST %>
              <%= image_tag("#{item}.svg", class: 'game-item__img') %>
            <% end %>
            <span class='game-item__name'>
              <%= item.humanize %>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="container-footer">
    <p class="container-description">
      Or you can create your own game with the following rules.
      <ol>
        1. Specify an <strong>odd number (Important!)</strong> of elements for the game, separated by a comma in the item list field, otherwise the game logic will be violated.
      </ol>
      <ol>
        2. The game will have a rule that each element will be weaker than the elements following it in the list in an amount equal to half of the total number of elemets. For example, in the game Rock, Hammer, Paper, Scissors, Robot - Rock will be stronger than Scissors and Robot, but weaker than Hammer and Paper
      </ol>
      <ol>
        3. Choose your variant from provided list.
      </ol>
    </p>

    <%= form_with url: new_game_path, data: { turbo_frame: 'modal' }, method: :get, class: 'footer__form' do |f| %>
      <div class="form_item">
        <%= f.label 'Items List' %>
        <%= f.text_field :items_list, class: 'footer__input', required: true %>
      </div>
      <div class="form_item">
        <%= f.label 'User throw' %>
        <%= f.text_field :user_throw, class: 'footer__input', required: true %>
      </div>
      <div class="form_item">
        <%= f.submit 'Make server throw', class: 'button'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <div class="modal">
    <h1 class="modal__title">
      <%= @result || 'Error' %>
    </h1>
    <p class="modal__description">
      <% if @throw_service.errors.empty? %>
         <%= "Curb throw #{@throw_service.server_throw}" %>
      <% else %>
        <div class="modal__error">
          <%= @throw_service.errors.join(', ') %>
        </div>
      <% end %>
    </p>
    <% if @items_list == GamesController::DEFAULT_ITEMS_LIST %>
      <%= image_tag("#{@throw_service.server_throw}.svg", class: 'modal__image') %>
    <% end %>
    <%= button_tag 'Ok', data: { controller: 'modals', action: 'modals#close' }, class: 'modal__button' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockPaperScissors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
    <script async="async" src="https://staging-static.mobilemonkey.com/js/115164265011439.js"></script>
  </head>

  <body>
    <%= turbo_frame_tag 'modal' %>
    <%= yield %>
  </body>
</html>